### ISSUE TITLE
Disabling the CircularDependencyException

### ISSUE THREAD

**Issue by Yihka** [digilist/SnakeDumper#18]
This is one of the better tools I've tested so far. However, it is clear that it cannot resolve CircularDependencies. But, wouldn't it be a solution to simply ignore these instead of throwing an exception? I had to comment this out, in order to make the tool work with my database, as I do have a circularDependency, even though I'm not planning to use this table in combination with this tool.

If it does horribly break something, maybe only throw an exception when it is used?

**Comment by digilist** [comment]
Yeah, good idea to check circular dependency only for tables that are actually included in the dump. I am not sure, when I will find time to work on it. If you can find some time, I'd appreciate a PR :+1:
