### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by robertfausk** [digilist/SnakeDumper#22]
http://digilist.de/snakedumper.phar redirects to https://digilist.de/digilist.de which responds with a 404 error code.

![image](https://user-images.githubusercontent.com/1651297/68184794-4a6cb800-ffa0-11e9-8ed4-4a8cf3bafc5e.png)

Even https://digilist.de and https://digilist.de/snakedumper.phar behave as explained above. Is it maybe a web server misconfiguration?

**Comment by digilist** [comment]
Hey Robert, thanks for reporting this. I fixed my webserver, the download is now available again.
