### ISSUE TITLE
Feature request: add SSL support 

### ISSUE THREAD

**Issue by pachico** [digilist/SnakeDumper#8]
It's a good practice to force connections to be secure, especially when dealing with production databases, which is what this library works with.
Unfortunately, I don't see any way to set SSL options, although it's supported by PDO.

What do you think?

**Comment by digilist** [comment]
That's true, good idea. I will take a look at it.

I think the best would be to allow setting PDO options in general (with PHP constants in the configuration file https://symfony.com/blog/new-in-symfony-3-2-php-constants-in-yaml-files)

**Comment by digilist** [comment]
I added the possibility to define PDO options in the config YAML. Is this what you need? I would really appreciate your feedback :relaxed:
